name 'chef_base_linux'
maintainer 'Daniel Jennings'
maintainer_email 'daniel.j.jennings@gmail.com'
license 'Apache-2.0'
description 'Applies common linux packages and configuration'
long_description 'Applies common linux packages and configuration'
version '1.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
depends 'vim'
depends 'git'
depends 'pathogen'
supports 'ubuntu'

issues_url 'https://github.com/JenningsDaniel/chef_base_linux/issues'
source_url 'https://github.com/JenningsDaniel/chef_base_linux'
