default['chef_base_linux']['home'] = '/home/vagrant'
default['chef_base_linux']['owner'] = 'vagrant'
default['chef_base_linux']['group'] = 'vagrant'
default['chef_base_linux']['vim']['gui_font'] = 'Hack:h9'
default['chef_base_linux']['vim']['color_scheme'] = 'solarized'
default['chef_base_linux']['vim']['background'] = 'light'
default['chef_base_linux']['vim']['use_pathogen'] = 'false'
default['chef_base_linux']['tmux']['color_scheme_variant'] = 'dark'
